apiVersion: v1
kind: Service
metadata:
  name: nibbledb
  labels:
    app: nibbledb
spec:
  ports:
    - port: 8000
      name: nibbledb
  clusterIP: None
  selector:
    app: nibbledb
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nibbledb
spec:
  serviceName: "nibbledb"
  replicas: 2
  selector:
    matchLabels:
      app: nibbledb
  template:
    metadata:
      labels:
        app: nibbledb
    spec:
      containers:
      - name: nibbledb
        image: jptmoore/nibbledb
        args: ["--db", "/home/nibble/mnt/db", "--enable-debug"]
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 1000m
            memory: 1000Mi
        ports:
        - containerPort: 8000
          name: nibbledb
        volumeMounts:
        - name: nibbledb
          mountPath: /home/nibble/mnt
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000          
  volumeClaimTemplates:
  - metadata:
      name: nibbledb
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
