apiVersion: v1
kind: Service
metadata:
  name: nibbledb
  labels:
    app: nibbledb
spec:
  ports:
    - port: 8000
      name: db
  clusterIP: None
  selector:
    app: nibbledb
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
spec:
  selector:
    matchLabels:
      app: nibbledb
  serviceName: "nibbledb"
  replicas: 4
  template:
    metadata:
      labels:
        app: nibbledb
    spec:
      containers:
        - name: nibbledb
          image: jptmoore/nibbledb
          args: ["--db", "/home/nibble/db"]
          resources:
            requests:
              cpu: 100m
              memory: 1000Mi
            limits:
              cpu: 1000m
              memory: 2000Mi
          ports:
            - containerPort: 8000
              name: db
